name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build the file
        run: |
          cd /home/runner/work/animated-weather-card/animated-weather-card
          yarn install
          yarn build

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/animated-weather-card/animated-weather-card/dist/animated-weather-card.js
          asset_name: animated-weather-card.js
          tag: ${{ github.ref }}
          overwrite: true

      - name: Verify HACS compliance
        uses: hacs/action@main
        with:
          category: plugin
